### ISSUE TITLE
NOAA Github Enterprise Transition 

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ss3diags#108]
What do we need to prepare ss3diags to nmfs-ost repository

- [x] Clean up existing issues 
  - [x] Merge fixes to #95 (Resolve PR issues #107)
  - [x] Resolve #106  
  - [x] Fix r4ss 1.50 dependency with read/write changes: use r4ss 1.49.3 for compat (#109)
- [x] Contact @e-perl-NOAA on the process to nmfs-ost 
- [ ] ~Coordinate with r4ss team to move ss3diags and r4ss to nmfs-ost (r4ss/r4ss#815)~ 
- [x] **Transfer ss3diags to nmfs-ost**
- [x] #117
- [x] Update README/documentation to direct to nmfs-ost/ss3diags.

What do we need to look out for? 
- PIFSCStockassements GitHub Projects & Teams do not carry over to GHEC. (Need to confirm) 
  - Project Boards & Teams can be rebult w/ repo issues.
- Issues, Github Actions are carried over to GHEC since it tied to the Repo.  
  - Ensure that Github Actions are not "Hardcoded" to PIFSCstockassessments.
- Github page (pkgdown) will not redirect automatically, but reconfigured pkgdown settings can rebuild github site. (#116)
- Email nmfs-ost for repo admin privileges.

**Comment by e-perl-NOAA** [comment]
@efletcherPIFSC GitHub will automatically redirect people from the old GitHub repo page to the new repo page for awhile. It will not automatically redirect the github.io page to the new one. You can create a redirect for that. The NEFSC org in GitHub enterprise has directions on how to do that [here](https://github.com/NEFSC/NEFSC-SVC-GitHub.github.io).

**Comment by efletcherPIFSC** [comment]
README update will depend on #116

**Comment by efletcherPIFSC** [comment]
Added #125 as a sub-issue. Transferring ss3diags **renv** environment to nmfs-ost may be a variable.

**Comment by efletcherPIFSC** [comment]
#126 updated README and documentation links. Thanks @arni-magnusson 
#132 resolved github site & github actions sub-issues
